# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraConfiguration.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraConfiguration(object):
    def setupUi(self, CameraConfiguration):
        CameraConfiguration.setObjectName("CameraConfiguration")
        CameraConfiguration.resize(640, 480)
        CameraConfiguration.setMaximumSize(QtCore.QSize(640, 480))
        CameraConfiguration.setToolTipDuration(-1)
        CameraConfiguration.setFrameShape(QtWidgets.QFrame.Box)
        CameraConfiguration.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label = QtWidgets.QLabel(CameraConfiguration)
        self.label.setGeometry(QtCore.QRect(200, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Linux Libertine G")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Cancel = QtWidgets.QPushButton(CameraConfiguration)
        self.Cancel.setGeometry(QtCore.QRect(514, 440, 111, 31))
        self.Cancel.setObjectName("Cancel")
        self.Accept = QtWidgets.QPushButton(CameraConfiguration)
        self.Accept.setGeometry(QtCore.QRect(390, 440, 111, 31))
        self.Accept.setObjectName("Accept")
        self.Apply = QtWidgets.QPushButton(CameraConfiguration)
        self.Apply.setGeometry(QtCore.QRect(270, 440, 111, 31))
        self.Apply.setObjectName("Apply")
        self.radioButton = QtWidgets.QRadioButton(CameraConfiguration)
        self.radioButton.setGeometry(QtCore.QRect(200, 40, 82, 17))
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(CameraConfiguration)
        self.radioButton_2.setGeometry(QtCore.QRect(310, 40, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame = QtWidgets.QFrame(CameraConfiguration)
        self.frame.setGeometry(QtCore.QRect(80, 120, 221, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dial = QtWidgets.QDial(self.frame)
        self.dial.setGeometry(QtCore.QRect(60, 60, 101, 111))
        self.dial.setObjectName("dial")
        self.frame_2 = QtWidgets.QFrame(CameraConfiguration)
        self.frame_2.setGeometry(QtCore.QRect(340, 120, 221, 241))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.dial_2 = QtWidgets.QDial(self.frame_2)
        self.dial_2.setGeometry(QtCore.QRect(50, 50, 111, 131))
        self.dial_2.setObjectName("dial_2")

        self.retranslateUi(CameraConfiguration)
        self.Cancel.clicked.connect(CameraConfiguration.close)
        self.Accept.clicked.connect(CameraConfiguration.close)
        self.Apply.clicked.connect(CameraConfiguration.update)
        self.radioButton.clicked['bool'].connect(self.frame.setEnabled)
        self.radioButton.clicked['bool'].connect(self.frame_2.setDisabled)
        self.radioButton_2.clicked['bool'].connect(self.frame.setDisabled)
        self.radioButton_2.clicked['bool'].connect(self.frame_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CameraConfiguration)

    def retranslateUi(self, CameraConfiguration):
        _translate = QtCore.QCoreApplication.translate
        CameraConfiguration.setWindowTitle(_translate("CameraConfiguration", "Frame"))
        self.label.setText(_translate("CameraConfiguration", "Camera Configuration"))
        self.Cancel.setText(_translate("CameraConfiguration", "Cancel"))
        self.Accept.setText(_translate("CameraConfiguration", "Accept"))
        self.Apply.setText(_translate("CameraConfiguration", "Apply"))
        self.radioButton.setText(_translate("CameraConfiguration", "Local Camera"))
        self.radioButton_2.setText(_translate("CameraConfiguration", "Transmition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraConfiguration = QtWidgets.QFrame()
    ui = Ui_CameraConfiguration()
    ui.setupUi(CameraConfiguration)
    CameraConfiguration.show()
    sys.exit(app.exec_())
